development:
  adapter: postgresql
  encoding: utf8
  database: jobprops
  pool: 5
  username: matt
  password:
  host: localhost

test: 
  adapter: postgresql
  encoding: utf8
  database: jobprops
  pool: 5
  username: matt
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: jobprops
  pool: 5
  username: matt
  password:
  host: localhost